language: node_js
node_js: "0.10"
before_install: npm install --global gulp && bower install
install: npm install
script: gulp
after_script: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
